### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by BryceLee** [shaopx/VideoClipEditViewTest#1]
Error:error: resource drawable/ic_video_record_back (aka com.spx.videoclipeditviewtest:drawable/ic_video_record_back) not found.
Error:error: resource drawable/ic_bg_video_next (aka com.spx.videoclipeditviewtest:drawable/ic_bg_video_next) not found.
Error:error: resource drawable/ic_record_filter (aka com.spx.videoclipeditviewtest:drawable/ic_record_filter) not found.
Error:error: resource drawable/ic_effect (aka com.spx.videoclipeditviewtest:drawable/ic_effect) not found.
Error:resource drawable/ic_video_record_back (aka com.spx.videoclipeditviewtest:drawable/ic_video_record_back) not found.
Error:resource drawable/ic_bg_video_next (aka com.spx.videoclipeditviewtest:drawable/ic_bg_video_next) not found.
Error:resource drawable/ic_record_filter (aka com.spx.videoclipeditviewtest:drawable/ic_record_filter) not found.
Error:resource drawable/ic_effect (aka com.spx.videoclipeditviewtest:drawable/ic_effect) not found.

**Comment by shaopx** [comment]
thanks for telling
